### ISSUE TITLE
Where to set maven reference

### ISSUE THREAD

**Issue by Ragadeepthi-Kotagiri** [frett27/jfgdb#1]
Hi, trying to execute samples in windows environment, but getting lot of errors. in Readme file i have seen set maven reference to jfgdb, where exactly we have to set it. am totally new to gradle and geodatabase. please guide me.

**Comment by frett27** [comment]
i don't think this is a project related issue, rather than maven usage

have you tried to follow this from the sample folder ?

https://github.com/frett27/jfgdb/blob/master/samples/README.md

using maven, you need to add the dependency , and repository reference in the POM, 
https://maven.apache.org/pom.html

i'll look for adding a MAVEN driven project example for speeding the usage for noobs.

**Comment by RAJESH-TECHMILEAGE** [comment]
hi,we are running this project in gradle but not in maven do we need to add any maven refrence ?

**Comment by frett27** [comment]
#2 this is close, looking for the other issue posted ?

**Comment by frett27** [comment]
look at the <repository>

 definition for maven, in POM , 

 <repositories>
    <repository>
      <id>central</id>
      <name>Maven Repository jfgdb</name>
      <layout>default</layout>
      <url>http://jfgdb.s3-website-eu-west-1.amazonaws.com/maven2</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>

see https://maven.apache.org/guides/introduction/introduction-to-the-pom.html

i might work, but i havn't tested yet, please give feedback in case the maven use is successfull, i could mention a proper working configuration.


Patrice
